In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split

credit_risk = pd.read_csv('/home/jovyan/work/datasets/credit_risk_dataset.csv')

credit_risk.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [5]:
credit_risk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB

In [21]:
y = credit_risk['loan_status'].copy()

X = credit_risk.copy()

X.drop(columns=['loan_status'], inplace=True)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.6,
    random_state=42
)

X_test, X_val, y_test, y_val = train_test_split(
    X_train,
    y_train,
    train_size=0.5,
    random_state=42
)

X_train.shape, y_train.shape, X_test.shape, y_test.shape, X_val.shape, y_val.shape

((19548, 11), (19548,), (9774, 11), (9774,), (9774, 11), (9774,))

In [22]:
obj_cols = [col for col in X_train.columns
           if X_train[col].dtype == 'object']
obj_cols

['person_home_ownership',
 'loan_intent',
 'loan_grade',
 'cb_person_default_on_file']

In [23]:
X_train.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
19718,28,35328,MORTGAGE,12.0,DEBTCONSOLIDATION,A,13000,NaN,0.37,N,9
27172,29,125000,MORTGAGE,2.0,MEDICAL,C,3500,13.98,0.03,N,8
8268,22,56902,MORTGAGE,6.0,DEBTCONSOLIDATION,A,12000,7.14,0.21,N,4
1836,22,30000,OWN,3.0,EDUCATION,C,8000,13.49,0.27,N,2
29903,37,59000,RENT,2.0,EDUCATION,D,4800,14.54,0.08,Y,14

In [25]:
for obj_col in obj_cols:
    print(X_train[obj_col].value_counts(dropna=False))

person_home_ownership
RENT        9833
MORTGAGE    8087
OWN         1571
OTHER         57
Name: count, dtype: int64
loan_intent
EDUCATION            3885
MEDICAL              3629
VENTURE              3398
PERSONAL             3320
DEBTCONSOLIDATION    3176
HOMEIMPROVEMENT      2140
Name: count, dtype: int64
loan_grade
A    6493
B    6266
C    3848
D    2207
E     560
F     135
G      39
Name: count, dtype: int64
cb_person_default_on_file
N    16093
Y     3455
Name: count, dtype: int64

In [27]:
X_train.corr(numeric_only=True)

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length
person_age,1.000000,0.190995,0.171764,0.049715,0.013528,-0.039516,0.856371
person_income,0.190995,1.000000,0.122492,0.244228,-0.001034,-0.234503,0.111927
person_emp_length,0.171764,0.122492,1.000000,0.113003,-0.053186,-0.045684,0.149866
loan_amnt,0.049715,0.244228,0.113003,1.000000,0.145542,0.578306,0.041463
loan_int_rate,0.013528,-0.001034,-0.053186,0.145542,1.000000,0.115453,0.015928
loan_percent_income,-0.039516,-0.234503,-0.045684,0.578306,0.115453,1.000000,-0.028803
cb_person_cred_hist_length,0.856371,0.111927,0.149866,0.041463,0.015928,-0.028803,1.000000